name = "muaraversa-api"

main = "worker.js"

compatibility_date = "2026-09-28"


[[d1_databases]]

binding = "DB"

database_name = "muaraversa-db"

database_id = "00bac109-ec9e-4ec5-be3e-e313d74c1269"
