CREATE TABLE IF NOT EXISTS roles (
  id INTEGER PRIMARY KEY,
  name TEXT UNIQUE NOT NULL
);

INSERT OR IGNORE INTO roles (id, name) VALUES
(1, 'ADMIN'),
(2, 'KEPALA_SEKOLAH'),
(3, 'GURU'),
(4, 'SISWA'),
(5, 'ORANG_TUA');
